import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Web3walletProvider from "@/hooks/web3wallet";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + "min-h-screen"}>
        <Web3walletProvider>
          <div>
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="dark"
            />
            <Navbar />
            {children}
          </div>
        </Web3walletProvider>
      </body>
    </html>
  );
}
